### ISSUE TITLE
Indentation schematics

### ISSUE THREAD

**Issue by aria-dev** [bazitur/brackets-python-tools#4]
As of August 2018, the indentation seems to be creating a few warnings, thereby slowing down the development process by quite a bit. 
Indentations occur after the colon(:) symbol is used and pressed Enter. That;s very helpful to quickly add spaces without hitting space 4 times. Tried adding one tab, but that returns a warning message, "whitespace contains tabs instead of spaces". That is not the issue here.
Even after we remove any whitespace in a new line and press enter, it creates a whitespace indentation.
Even simple editors, don't do that.
Indentation has to be turned thereoff, when a  *blank new line without whitespaces* is created.

**Comment by bazitur** [comment]
Hello @vdevel00,
Auto-indentation is a part of underlying CodeMirror code editor, not this extension. 
Have you checked that in Brackets' settings indentation with whitespace is enabled?

**Comment by aria-dev** [comment]
Yes, I did, and disabling the option worked. It was not the extension at fault.
